USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::******:role/snowflake_s3_role'
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://snowflake-s3-data-loading/');

DESC INTEGRATION S3_INTEGRATION;